{
  "openapi": "3.0.1",
  "info": {
    "title": "77-Bit API",
    "description": "An API for interacting with the 77-Bit L2 blockchain.",
    "termsOfService": "https://77-bit.com/terms",
    "license": {
      "name": "License",
      "url": "https://77-bit.com/license"
    },
    "version": "1.0",
    "x-logo": {
      "url": "https://pbs.twimg.com/profile_images/1642220143915696128/x3yCWwbE_400x400.jpg",
      "altText": "77-Bit logo"
    }
  },
  "servers": [
    {
      "url": "https://testnet-api.77-bit.com",
      "description": "Testnet server (Goerli)."
    },
    {
      "url": "https://api.77-bit.com",
      "description": "Mainnet server (Ethereum)."
    }
  ],
  "paths": {
    "/api/v1/assets": {
      "post": {
        "tags": [
          "Asset"
        ],
        "security": [
          {
            "oauth2": [
              "write:assets"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Asset"
        ],
        "summary": "Get All Assets",
        "description": "This endpoint fetches all assets in the system, with support for filters and pagination.",
        "operationId": "GetAllAssets",
        "security": [
          {
            "oauth2": [
              "read:assets"
            ]
          }
        ]
      }
    },
    "/api/v1/assets/{assetId}": {
      "get": {
        "tags": [
          "Asset"
        ],
        "summary": "Get Asset",
        "description": "This endpoint fetches a specific asset by ID.",
        "operationId": "GetAsset",
        "security": [
          {
            "oauth2": [
              "read:assets"
            ]
          }
        ]
      }
    },
    "/api/v1/deposits/signable": {
      "post": {
        "tags": [
          "Deposit"
        ],
        "summary": "Returns the deposit details for a given asset.",
        "description": "This endpoint returns the deposit details for a given user, asset, and data availability mode.",
        "operationId": "GetSignableDeposit",
        "security": [
          {
            "oauth2": [
              "read:vaults",
              "write:vaults"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplaces": {
      "get": {
        "tags": [
          "Marketplace"
        ],
        "summary": "List Marketplaces",
        "description": "This endpoint retrieves paginated a list of marketplaces.",
        "operationId": "ListMarketplaces",
        "security": [
          {
            "oauth2": [
              "read:marketplaces"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Create Marketplace",
        "description": "This endpoint creates a marketplace.",
        "operationId": "CreateMarketplace",
        "security": [
          {
            "oauth2": [
              "write:marketplaces"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplaces/{marketplaceId}": {
      "get": {
        "tags": [
          "Order"
        ],
        "summary": "Get Marketplace",
        "description": "This endpoint retrieves a marketplace by ID.",
        "operationId": "GetMarketplaces",
        "security": [
          {
            "oauth2": [
              "read:marketplaces"
            ]
          }
        ]
      }
    },
    "/api/v1/mint": {
      "post": {
        "tags": [
          "Mint"
        ],
        "summary": "Mint Assets",
        "description": "This endpoint allows for the minting of fungible and non-fungible assets.",
        "operationId": "MintAssets",
        "security": [
          {
            "oauth2": [
              "mint:assets"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplaces/{marketplaceId}/orders": {
      "get": {
        "tags": [
          "Order"
        ],
        "summary": "List Marketplace Orders",
        "description": "This endpoint retrieves paginated a list of marketplace orders.",
        "operationId": "ListMarketplaceOrders",
        "security": [
          {
            "oauth2": [
              "read:marketplaces"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Order"
        ],
        "summary": "Submit Order",
        "description": "This endpoint submits a marketplace order.",
        "operationId": "SubmitOrder",
        "security": [
          {
            "oauth2": [
              "write:orders"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplaces/{marketplaceId}/orders/{orderId}": {
      "get": {
        "tags": [
          "Order"
        ],
        "summary": "Get Marketplace Order",
        "description": "This endpoint retrieves a marketplace order by ID.",
        "operationId": "GetMarketplaceOrder",
        "security": [
          {
            "oauth2": [
              "read:orders"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Order"
        ],
        "summary": "Cancel Order",
        "description": "This endpoint cancels a marketplace order.",
        "operationId": "CancelOrder",
        "security": [
          {
            "oauth2": [
              "write:orders"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplaces/{marketplaceId}/orders/signable": {
      "post": {
        "tags": [
          "Order"
        ],
        "summary": "Get Signable Order",
        "description": "This endpoint allows for fetching signable orders.",
        "operationId": "GetSignableOrder",
        "security": [
          {
            "oauth2": [
              "write:orders"
            ]
          }
        ]
      }
    },
    "/api/v1/settlements": {
      "post": {
        "tags": [
          "Settlement"
        ],
        "summary": "Submit Settlement",
        "description": "This endpoint submits an order settlement.",
        "operationId": "SubmitSettlement",
        "security": [
          {
            "oauth2": [
              "write:settlements"
            ]
          }
        ]
      }
    },
    "/api/v1/transactions": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "Get All Transactions",
        "description": "This endpoint fetches all transactions submitted by the system, with support for filters and pagination.",
        "operationId": "GetAllTransactions",
        "security": [
          {
            "oauth2": [
              "read:transactions"
            ]
          }
        ]
      }
    },
    "/api/v1/transactions/{transactionId}": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "Get Transaction",
        "description": "This endpoint fetches a specific transaction by ID.",
        "operationId": "GetTransaction",
        "security": [
          {
            "oauth2": [
              "read:transactions"
            ]
          }
        ]
      }
    },
    "/api/v1/transfers": {
      "post": {
        "tags": [
          "Transfer"
        ],
        "summary": "Transfer Asset",
        "description": "This endpoint allows for transferring assets between users.",
        "operationId": "Transfer",
        "security": [
          {
            "oauth2": [
              "write:transfers"
            ]
          }
        ]
      }
    },
    "/api/v1/transfers/signable": {
      "get": {
        "tags": [
          "Transfer"
        ],
        "summary": "Get Signable Details",
        "description": "This endpoint allows for fetching details of a transfer to be signed",
        "operationId": "TransferSignable",
        "security": [
          {
            "oauth2": [
              "write:transfers"
            ]
          }
        ]
      }
    },
    "/api/v1/users": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Register new User",
        "description": "This endpoint registers a user.",
        "operationId": "RegisterUser",
        "security": [
          {
            "oauth2": [
              "write:users"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get All Users",
        "description": "This endpoint fetches all users.",
        "operationId": "GetAllUsers",
        "security": [
          {
            "oauth2": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/api/v1/users/{userId}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User",
        "description": "This endpoint fetches a specific user by ID.",
        "operationId": "GetUser",
        "security": [
          {
            "oauth2": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/api/v1/vaults/withdraw": {
      "post": {
        "tags": [
          "Withdraw"
        ],
        "summary": "Withdraw Asset",
        "description": "This endpoint allows for withdrawing assets from SevenSevenBit.",
        "operationId": "Withdraw",
        "security": [
          {
            "oauth2": [
              "write:vaults"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://sevensevenbit-dev.eu.auth0.com/oauth/token",
            "scopes": {
              "write:users": "Access user write operations.",
              "read:users": "Access user read operations.",
              "write:assets": "Access asset write operations.",
              "read:assets": "Access asset read operations.",
              "mint:assets": "Access mint operations.",
              "read:vaults": "Access vault read operations.",
              "write:transfers": "Access transfer write operations.",
              "write:settlements": "Access settlement write operations.",
              "read:transactions": "Access tarnsaction read operations."
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "User",
      "description": "Manage user-related operations."
    },
    {
      "name": "Asset",
      "description": "Manage asset-related operations."
    },
    {
      "name": "Mint",
      "description": "Manage minting-related operations."
    },
    {
      "name": "Transfer",
      "description": "Manage asset transfer operations."
    },
    {
      "name": "Transaction",
      "description": "Manage transaction-related operations."
    },
    {
      "name": "Withdraw",
      "description": "Manage asset withdrawal operations."
    },
    {
      "name": "Fee",
      "description": "Manage fee configuration operations."
    },
    {
      "name": "Order",
      "description": "Manage order-related operations."
    },
    {
      "name": "Settlement",
      "description": "Manage asset settlement operations."
    },
    {
      "name": "Marketplace",
      "description": "Manage marketplace-related operations."
    },
    {
      "name": "Deposit",
      "description": "Manage asset deposit operations."
    }
  ]
}