CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "AddressTransactions" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "BlockNumber" character varying(100) NOT NULL,
        "Hash" character varying(67) NOT NULL,
        "Address" character varying(43) NOT NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_AddressTransactions" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "BlockProgress" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "LastBlockProcessed" character varying(43) NOT NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_BlockProgress" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "Blocks" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "BlockNumber" character varying(100) NOT NULL,
        "Hash" character varying(67) NOT NULL,
        "ParentHash" character varying(67) NOT NULL,
        "Nonce" character varying(100) NULL,
        "ExtraData" text NULL,
        "Difficulty" character varying(100) NULL,
        "TotalDifficulty" character varying(100) NULL,
        "Size" character varying(100) NULL,
        "Miner" character varying(43) NULL,
        "GasLimit" character varying(100) NULL,
        "GasUsed" character varying(100) NULL,
        "Timestamp" character varying(100) NULL,
        "TransactionCount" bigint NOT NULL,
        "BaseFeePerGas" text NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_Blocks" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "Contracts" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "Address" character varying(43) NULL,
        "Name" character varying(255) NULL,
        "ABI" text NULL,
        "Code" text NULL,
        "Creator" character varying(43) NULL,
        "TransactionHash" character varying(67) NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_Contracts" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "TransactionLogs" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "TransactionHash" character varying(67) NOT NULL,
        "LogIndex" character varying(100) NULL,
        "Address" character varying(43) NULL,
        "EventHash" character varying(67) NULL,
        "IndexVal1" character varying(67) NULL,
        "IndexVal2" character varying(67) NULL,
        "IndexVal3" character varying(67) NULL,
        "Data" text NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_TransactionLogs" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "TransactionLogVmStacks" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "Address" character varying(43) NULL,
        "TransactionHash" character varying(67) NULL,
        "StructLogs" text NULL,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        CONSTRAINT "PK_TransactionLogVmStacks" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE TABLE "Transactions" (
        "RowIndex" integer GENERATED BY DEFAULT AS IDENTITY,
        "RowCreated" timestamp with time zone NULL,
        "RowUpdated" timestamp with time zone NULL,
        "BlockHash" character varying(67) NULL,
        "BlockNumber" character varying(100) NOT NULL,
        "Hash" character varying(67) NOT NULL,
        "AddressFrom" character varying(43) NULL,
        "TimeStamp" character varying(100) NULL,
        "TransactionIndex" character varying(100) NULL,
        "Value" character varying(100) NULL,
        "AddressTo" character varying(43) NULL,
        "Gas" character varying(100) NULL,
        "GasPrice" character varying(100) NULL,
        "Input" text NULL,
        "Nonce" character varying(100) NULL,
        "Failed" boolean NOT NULL,
        "ReceiptHash" character varying(67) NULL,
        "GasUsed" character varying(100) NULL,
        "CumulativeGasUsed" character varying(100) NULL,
        "EffectiveGasPrice" text NULL,
        "HasLog" boolean NOT NULL,
        "Error" text NULL,
        "HasVmStack" boolean NOT NULL,
        "NewContractAddress" character varying(43) NULL,
        "FailedCreateContract" boolean NOT NULL,
        "MaxFeePerGas" text NULL,
        "MaxPriorityFeePerGas" text NULL,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("RowIndex")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_AddressTransactions_Address" ON "AddressTransactions" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE UNIQUE INDEX "IX_AddressTransactions_BlockNumber_Hash_Address" ON "AddressTransactions" ("BlockNumber", "Hash", "Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_AddressTransactions_Hash" ON "AddressTransactions" ("Hash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_BlockProgress_LastBlockProcessed" ON "BlockProgress" ("LastBlockProcessed");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE UNIQUE INDEX "IX_Blocks_BlockNumber_Hash" ON "Blocks" ("BlockNumber", "Hash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_Contracts_Address" ON "Contracts" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE UNIQUE INDEX "IX_Contracts_Name" ON "Contracts" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogs_Address" ON "TransactionLogs" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogs_EventHash" ON "TransactionLogs" ("EventHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogs_IndexVal1" ON "TransactionLogs" ("IndexVal1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogs_IndexVal2" ON "TransactionLogs" ("IndexVal2");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogs_IndexVal3" ON "TransactionLogs" ("IndexVal3");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE UNIQUE INDEX "IX_TransactionLogs_TransactionHash_LogIndex" ON "TransactionLogs" ("TransactionHash", "LogIndex");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogVmStacks_Address" ON "TransactionLogVmStacks" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_TransactionLogVmStacks_TransactionHash" ON "TransactionLogVmStacks" ("TransactionHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_Transactions_AddressFrom" ON "Transactions" ("AddressFrom");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_Transactions_AddressTo" ON "Transactions" ("AddressTo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE UNIQUE INDEX "IX_Transactions_BlockNumber_Hash" ON "Transactions" ("BlockNumber", "Hash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_Transactions_Hash" ON "Transactions" ("Hash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    CREATE INDEX "IX_Transactions_NewContractAddress" ON "Transactions" ("NewContractAddress");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220912134930_InitialSetup') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220912134930_InitialSetup', '6.0.8');
    END IF;
END $EF$;
COMMIT;

