= TransactionStream Service
Copyright (c) 2022 Three Sigma. All rights reserved


This canvas describes the `TransactionStream Service`, which is part of the https://threesigma.xyz[SevenSevenBit] project.

[cols="8*"]
|===
3+a| Name: 5+a| TransactionStream

3+a| *Description:*
5+a|

The TransactionStream Service provides an API for submitting transaction to the https://docs.starkware.co/starkex/api/spot/gateway.html[StarkEx Gateway].

8+a| *Capabilities*
8+a|
Submit transactions to the https://docs.starkware.co/starkex/api/spot/gateway.html[StarkEx Gateway] with retry patterns and resilience mechanisms.
8+| *Service API*
3+| Commands 3+| Queries 2+| Events Published
3+a| Synchronous:

* N/A

Asynchronous:

* Submit Transaction

 3+a| N/A 2+a|

* Transaction Submitted

3+| Non-functional requirements 5+a|

* 99.95% availability
* 10,000 txs/second

8+| *Observability*
8+| Key metrics
8+a|

* submitted_transactions
* reverted_transactions

4+| Health check endpoint
4+| /healthz



8+| *Implementation*
8+| Domain Model
8+a| * N/A
8+| *Dependencies*
4+| Invokes 4+| Subscribes to
4+a|

N/A

 4+a| Saga reply channels:

* Stream Transaction Saga

|===