name: Master workflow

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: sevensevenbit.azurecr.io
  OPERATOR_IMAGE_NAME: sevensevenbit/sevensevenbit-api
  WORKER_IMAGE_NAME: sevensevenbit/sevensevenbit-worker
  TRANSACTION_STREAM_SERVICE_IMAGE_NAME: sevensevenbit/sevensevenbit-transaction-stream-service
  TRANSACTION_ID_SERVICE_IMAGE_NAME: sevensevenbit/sevensevenbit-transaction-id-service
  TRANSACTION_SAGA_SERVICE_IMAGE_NAME: sevensevenbit/sevensevenbit-saga-service
  OPERATOR_MIGRATIONS_IMAGE_NAME: sevensevenbit/sevensevenbit-operator-migrations
  BLOCKCHAIN_MIGRATIONS_IMAGE_NAME: sevensevenbit/sevensevenbit-blockchain-migrations

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    env:
      MAJOR: 1
      MINOR: 0
    steps:
      - id: version
        name: Create Release
        run: echo "value=${{ env.MAJOR }}.${{ env.MINOR }}.$(date +%y%j | tr -d '\n').$(date +%H%M | tr -d '\n')" >> $GITHUB_OUTPUT
    outputs:
      release_version: ${{ steps.version.outputs.value }}
  
  # Ideally this job would be split in 3, but because the github runners don't share context between jobs 
  # and using shared storage surpasses the limit quickly, we have to have these 3 unified
  build-push:
    name: Build and Push solution
    runs-on: ubuntu-latest
    needs: release
    
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment vars
        run: |
          echo "COMMIT_TAG=$GITHUB_SHA" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{needs.release.outputs.release_version}}" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          touch .env
          make build

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: sevensevenbit.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Tag docker image
        run: |
          docker tag ${{ env.OPERATOR_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.OPERATOR_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.WORKER_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.WORKER_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.TRANSACTION_STREAM_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.TRANSACTION_STREAM_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.TRANSACTION_ID_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.TRANSACTION_ID_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.TRANSACTION_SAGA_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.TRANSACTION_SAGA_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.OPERATOR_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.OPERATOR_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker tag ${{ env.BLOCKCHAIN_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}} ${{ env.REGISTRY }}/${{ env.BLOCKCHAIN_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}}

      - name: Push Operator Docker image to private azure registry feed
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.OPERATOR_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.WORKER_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.TRANSACTION_STREAM_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.TRANSACTION_ID_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.TRANSACTION_SAGA_SERVICE_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.OPERATOR_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
          docker push ${{ env.REGISTRY }}/${{ env.BLOCKCHAIN_MIGRATIONS_IMAGE_NAME }}:${{needs.release.outputs.release_version}}
 
      - name: Update SDKs
        run: gh workflow run "Update Client SDKs" -f ref=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_CLIENT_SDK_UPDATE }}