name: Swagger workflow

on:
  push:
    branches:
      - 'master'

jobs:
  publish-openapi-spec:
    name: Publish OpenApi Spec
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.pr.outputs.commit_sha }}
    env:
      dotnet-version: '6.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Setup .NET Core SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore

      - name: Generate OpenApi spec
        run: |
          mkdir -p openapi
          dotnet build src/SevenSevenBit.Operator.Web --no-restore
        
      - name: Publish
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: openapi
          container_name: sevensevenbit-swagger-json
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          extra_args: '--pattern *.json'
          overwrite: 'true'
          
  generate-sdks:
    name: Generate and publish client SDKs
    runs-on: ubuntu-latest
    needs: publish-openapi-spec
    
    strategy:
      matrix:
        generator: [ csharp ]
        include:
          - generator: csharp
            config: .github/workflows/config/csharp.json
            template: .github/workflows/templates/csharp
            repo: threesigmaxyz/sevensevenbit-dotnet-client
            remove: "src docs"
#          - generator: python
#            config: .github/workflows/config/python.json
#            template: .github/workflows/templates/python
#            repo: threesigmaxyz/sevensevenbit-python-client
#            remove: "src docs"
          - generator: typescript-node
            config: .github/workflows/config/node.json
            template: .github/workflows/templates/node
            repo: threesigmaxyz/sevensevenbit-node-client
            remove: "src docs"
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.publish-openapi-spec.outputs.commit_hash }}

      - name: Generate client SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.generator }}
          openapi-file: openapi/swagger.json
          config-file: ${{ matrix.config }}
          template-dir: ${{ matrix.template }}

      - name: Checkout client repo
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN_FOR_CLIENT_SDK_UPDATE }}
          path: ${{ matrix.repo }}

      - name: Copy contents to client repo
        run: |
          cd ${{ matrix.repo }}
          rm -Rf ${{ matrix.remove }}
          cd -
          cp -r ${{ matrix.generator }}-client/* ${{ matrix.repo }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          path: ${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN_FOR_CLIENT_SDK_UPDATE }}
          branch: openapi-${{ matrix.generator }}
          delete-branch: true
          author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
          title: 'Update client SDK'
          commit-message: 'feat: automated change' 
          labels: |
            enhancement
            automated pr

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"